[workspace]
members = [
    "assert-owner",
    "common",
    "dex",
    "dex/crank",
    "dex/permissioned",
    "pool",
    "pool/schema",
    "pool/examples/admin-controlled",
    "pool/examples/simple",
]
